/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asn7;

import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jgc11
 */
public class BookListingsUI extends javax.swing.JFrame {
    private ConSingleton con;
    private SearchListingsUI prevSearch;
    
    /**
     * Creates new form BookListingsUI
     */
    public BookListingsUI() {
        initComponents();
        con = ConSingleton.getInstance();
        prevSearch = con.getPrevSearch();
        if (prevSearch != null) {
            bookID.setText(String.valueOf(con.getListingId()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bookID = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        bookStartDate = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        bookEndDate = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        bookGuestName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bookNumGuests = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        bookBookBtn = new javax.swing.JButton();
        bookBackBtn = new javax.swing.JButton();
        bookStatusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Book Listing"));

        jLabel1.setText("Listing ID:");

        bookStartDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        bookStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookStartDateActionPerformed(evt);
            }
        });

        jLabel2.setText("Stay From (yyyy-MM-dd):");

        bookEndDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        bookEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookEndDateActionPerformed(evt);
            }
        });

        jLabel3.setText("Stay To (yyyy-MM-dd):");

        bookGuestName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookGuestNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Guest Name:");

        bookNumGuests.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel5.setText("Number of Guests:");

        bookBookBtn.setText("Book");
        bookBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBookBtnActionPerformed(evt);
            }
        });

        bookBackBtn.setText("Back");
        bookBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bookBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(331, 331, 331))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bookBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookNumGuests)
                    .addComponent(bookID)
                    .addComponent(bookStartDate)
                    .addComponent(bookEndDate)
                    .addComponent(bookGuestName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(285, 285, 285))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookNumGuests, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(bookBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookStartDateActionPerformed

    private void bookEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookEndDateActionPerformed

    private void bookGuestNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookGuestNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookGuestNameActionPerformed

    private void bookBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBackBtnActionPerformed
        // TODO add your handling code here:
        if (prevSearch != null) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    prevSearch.setVisible(true);
                }
            });
            this.dispose();
            return;
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_bookBackBtnActionPerformed

    private void bookBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBookBtnActionPerformed
        // TODO add your handling code here:
        if (bookID.getText().isEmpty() || bookStartDate.getText().isEmpty() || bookEndDate.getText().isEmpty()
                || bookGuestName.getText().isEmpty() || bookNumGuests.getText().isEmpty()) {
            bookStatusLabel.setText("Please fill out all fields.");
            return;
        }
        String startDate = bookStartDate.getText();
        String endDate = bookEndDate.getText();
        java.util.Date date1 = null;
        java.util.Date date2 = null;
        try {
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse(startDate);
            date2 = new SimpleDateFormat("yyyy-MM-dd").parse(endDate);
        } catch (ParseException ex) {
            System.out.println(ex.toString());
        }
        if (date1.after(date2)) {
            bookStatusLabel.setText("Please ensure Stay To date is later than Stay From date.");
            return;
        }
        String statement = buildStatement();
        System.out.println(statement);
        if (con.update(statement)) {
            bookStatusLabel.setText("Successfully booked!");
        } else {
            bookStatusLabel.setText("Failed to book.");
        }
    }//GEN-LAST:event_bookBookBtnActionPerformed

    private String buildStatement() {
        String getQuery = "SELECT MAX(bookings.id) AS id FROM bookings;";
        ResultSet rs = con.query(getQuery);
        String id = "";
        try {
            while (rs.next()) {
                id = String.valueOf(rs.getInt("id") + 1);
                System.out.println("BOOKING ID:" + id);
            }
            rs.close();            
        } catch (SQLException se) {
            System.out.println("\nSQL Exception occurred, the state : "
                    + se.getSQLState() + "\nMessage:\n" + se.getMessage() + "\n");
            return null;
        }
        String query = "INSERT INTO bookings (\n" +
                        "	bookings.id,\n" +
                        "	bookings.listing_id,\n" +
                        "	bookings.guest_name,\n" +
                        "	bookings.stay_from,\n" +
                        "	bookings.stay_to,\n" +
                        "	bookings.number_of_guests) \n" +
                        "VALUES ( \n" +
                        id + ", \n" +
                        bookID.getText() + ", \n" +
                        "'" + bookGuestName.getText() + "', \n" +
                        "'" + bookStartDate.getText() + "', \n" +
                        "'" + bookEndDate.getText() + "', \n" +
                        bookNumGuests.getText() + ");";
        return query;                        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookListingsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookListingsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookListingsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookListingsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookListingsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBackBtn;
    private javax.swing.JButton bookBookBtn;
    private javax.swing.JFormattedTextField bookEndDate;
    private javax.swing.JTextField bookGuestName;
    private javax.swing.JFormattedTextField bookID;
    private javax.swing.JFormattedTextField bookNumGuests;
    private javax.swing.JFormattedTextField bookStartDate;
    private javax.swing.JLabel bookStatusLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
